spec_version: v1
kind: connection
app_id: ibm_sip_oauth2_client_credentials
environments:
    draft:
        kind: oauth_auth_client_credentials_flow
        type: member
        sso: false
        server_url: "{IBM_SIP[base_url]}"
        credentials:
            token_url: "{IBM_SIP[token_url]}"
            client_id: "{IBM_SIP[client_id]}"
            client_secret: "{IBM_SIP[client_secret]}"
            scope: "{IBM_SIP[scope]}"
    live:
        kind: oauth_auth_client_credentials_flow
        type: member
        sso: false
        server_url: "{IBM_SIP[base_url]}"
        credentials:
            token_url: "{IBM_SIP[token_url]}"
            client_id: "{IBM_SIP[client_id]}"
            client_secret: "{IBM_SIP[client_secret]}"
            scope: "{IBM_SIP[scope]}"
