spec_version: v1
kind: connection
app_id: red_hat_ansible_conn_type
environments:
  draft:
    kind: oauth_auth_code_flow
    type: member
    sso: false
    server_url: "{RED_HAT_ANSIBLE[base_url]}"
    credentials:
      token_url: "{RED_HAT_ANSIBLE[token_url]}"
      authorization_url: "{RED_HAT_ANSIBLE[auth_url]}"
      client_id: "{RED_HAT_ANSIBLE[client_id]}"
      client_secret: "{RED_HAT_ANSIBLE[client_secret]}"
      scope: "{RED_HAT_ANSIBLE[scope]}"
  live:
    kind: oauth_auth_code_flow
    type: member
    sso: false
    server_url: "{RED_HAT_ANSIBLE[base_url]}"
    credentials:
      token_url: "{RED_HAT_ANSIBLE[token_url]}"
      authorization_url: "{RED_HAT_ANSIBLE[auth_url]}"
      client_id: "{RED_HAT_ANSIBLE[client_id]}"
      client_secret: "{RED_HAT_ANSIBLE[client_secret]}"
      scope: "{RED_HAT_ANSIBLE[scope]}"
