spec_version: v1
kind: connection
app_id: ariba_base_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{ARIBA[base_url]}"
        credentials:
          token_url: "{ARIBA[token_url]}"
          realm: "{ARIBA[realm]}"
          buyer_anid: "{ARIBA[buyer_anid]}"
          base_url: "{ARIBA[base_url]}"
          password_adapter: "{ARIBA[password_adapter]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{ARIBA[base_url]}"
        credentials:
          token_url: "{ARIBA[token_url]}"
          realm: "{ARIBA[realm]}"
          buyer_anid: "{ARIBA[buyer_anid]}"
          base_url: "{ARIBA[base_url]}"
          password_adapter: "{ARIBA[password_adapter]}"