spec_version: v1
kind: connection
app_id: ariba_supplier_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        credentials:
          client_id: "{ARIBA[SUPPLIER][client_id]}"
          client_secret: "{ARIBA[SUPPLIER][client_secret]}"
          api_key: "{ARIBA[SUPPLIER][api_key]}"
    live:
        kind: key_value
        type: team
        sso: false
        credentials:
          client_id: "{ARIBA[SUPPLIER][client_id]}"
          client_secret: "{ARIBA[SUPPLIER][client_secret]}"
          api_key: "{ARIBA[SUPPLIER][api_key]}"