spec_version: v1
kind: connection
app_id: ariba_master_data_retrieval_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        credentials:
          client_id: "{ARIBA[MASTER_DATA_RETRIEVAL][client_id]}"
          client_secret: "{ARIBA[MASTER_DATA_RETRIEVAL][client_secret]}"
          api_key: "{ARIBA[MASTER_DATA_RETRIEVAL][api_key]}"
    live:
        kind: key_value
        type: team
        sso: false
        credentials:
          client_id: "{ARIBA[MASTER_DATA_RETRIEVAL][client_id]}"
          client_secret: "{ARIBA[MASTER_DATA_RETRIEVAL][client_secret]}"
          api_key: "{ARIBA[MASTER_DATA_RETRIEVAL][api_key]}"