spec_version: v1
kind: connection
app_id: amazon_s3_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        credentials:
          access_key: "{AMAZON_S3[access_key]}"
          secret_key: "{AMAZON_S3[secret_key]}"
          region: "{AMAZON_S3[region]}"
    live:
        kind: key_value
        type: team
        sso: false
        credentials:
          access_key: "{AMAZON_S3[access_key]}"
          secret_key: "{AMAZON_S3[secret_key]}"
          region: "{AMAZON_S3[region]}"
