spec_version: v1
kind: connection
app_id: dynamics365_oauth2_client_credentials
environments:
    draft:
        kind: oauth_auth_client_credentials_flow
        type: team
        sso: false
        server_url: "{DYNAMICS365[base_url]}"
        credentials:
            token_url: "{DYNAMICS365[token_url]}"
            client_id: "{DYNAMICS365[client_id]}"
            client_secret: "{DYNAMICS365[client_secret]}"
            scope: "{DYNAMICS365[scope]}"
    live:
        kind: oauth_auth_client_credentials_flow
        type: team
        sso: false
        server_url: "{DYNAMICS365[base_url]}"
        credentials:
            token_url: "{DYNAMICS365[token_url]}"
            client_id: "{DYNAMICS365[client_id]}"
            client_secret: "{DYNAMICS365[client_secret]}"
            scope: "{DYNAMICS365[scope]}"
