spec_version: v1
kind: connection
app_id: workday_manager_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{WORKDAY[base_url]}"
        credentials:
            bearer_token: "{WORKDAY[MANAGER][bearer_token]}"
            refresh_token: "{WORKDAY[MANAGER][refresh_token]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{WORKDAY[base_url]}"
        credentials:
            bearer_token: "{WORKDAY[MANAGER][bearer_token]}"
            refresh_token: "{WORKDAY[MANAGER][refresh_token]}"
