spec_version: v1
kind: connection
app_id: adobe_workfront_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{ADOBEWORKFRONT[base_url]}"
        credentials:
          token_url: "{ADOBEWORKFRONT[token_url]}"
          client_id: "{ADOBEWORKFRONT[client_id]}"
          client_secret: "{ADOBEWORKFRONT[client_secret]}"
          bearer_token: "{ADOBEWORKFRONT[bearer_token]}"
          refresh_token: "{ADOBEWORKFRONT[refresh_token]}"
          base_url: "{ADOBEWORKFRONT[base_url]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{ADOBEWORKFRONT[base_url]}"
        credentials:
          token_url: "{ADOBEWORKFRONT[token_url]}"
          client_id: "{ADOBEWORKFRONT[client_id]}"
          client_secret: "{ADOBEWORKFRONT[client_secret]}"
          bearer_token: "{ADOBEWORKFRONT[bearer_token]}"
          refresh_token: "{ADOBEWORKFRONT[refresh_token]}"
          base_url: "{ADOBEWORKFRONT[base_url]}"
