spec_version: v1
kind: connection
app_id: ibm_planning_analytics_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{IBM_PLANNING_ANALYTICS[base_url]}"
        credentials:
            tenant_id: "{IBM_PLANNING_ANALYTICS[tenant_id]}"
            model_name: "{IBM_PLANNING_ANALYTICS[model_name]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{IBM_PLANNING_ANALYTICS[base_url]}"
        credentials:
            tenant_id: "{IBM_PLANNING_ANALYTICS[tenant_id]}"
            model_name: "{IBM_PLANNING_ANALYTICS[model_name]}"