"""Rename Item to Feedback and update fields for feedback tracking

Revision ID: 31a7f30eb5f8
Revises: 1a31ce608336
Create Date: 2026-02-19 16:03:09.110117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '31a7f30eb5f8'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('feedback_comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('rated_message', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('user_message_before', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###
