spec_version: v1
kind: connection
app_id: workday_base_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{WORKDAY[base_url]}"
        credentials:
            token_url: "{WORKDAY[token_url]}"
            client_id: "{WORKDAY[client_id]}"
            client_secret: "{WORKDAY[client_secret]}"
            tenant_name: "{WORKDAY[tenant_name]}"
            base_url: "{WORKDAY[base_url]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{WORKDAY[base_url]}"
        credentials:
            token_url: "{WORKDAY[token_url]}"
            client_id: "{WORKDAY[client_id]}"
            client_secret: "{WORKDAY[client_secret]}"
            tenant_name: "{WORKDAY[tenant_name]}"
            base_url: "{WORKDAY[base_url]}"
