spec_version: v1
kind: connection
app_id: salesloft_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{SALESLOFT[base_url]}"
        credentials:
            base_url: "{SALESLOFT[base_url]}"
            token_url: "{SALESLOFT[token_url]}"
            client_id: "{SALESLOFT[client_id]}"
            client_secret: "{SALESLOFT[client_secret]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{SALESLOFT[base_url]}"
        credentials:
            base_url: "{SALESLOFT[base_url]}"
            token_url: "{SALESLOFT[token_url]}"
            client_id: "{SALESLOFT[client_id]}"
            client_secret: "{SALESLOFT[client_secret]}"
