spec_version: v1
kind: connection
app_id: dnb_sales_oauth2_client_credentials
environments:
    draft:
        kind: oauth_auth_client_credentials_flow
        type: member
        sso: false
        server_url: "{DNB[base_url]}"
        credentials:
            token_url: "{DNB[token_url]}"
            client_id: "{DNB[SALES][client_id]}"
            client_secret: "{DNB[SALES][client_secret]}"
            scope: "{DNB[SALES][scope]}"
    live:
        kind: oauth_auth_client_credentials_flow
        type: member
        sso: false
        server_url: "{DNB[base_url]}"
        credentials:
            token_url: "{DNB[token_url]}"
            client_id: "{DNB[SALES][client_id]}"
            client_secret: "{DNB[SALES][client_secret]}"
            scope: "{DNB[SALES][scope]}"
