spec_version: v1
kind: connection
app_id: jira_oauth2_auth_code
environments:
    draft:
        kind: oauth_auth_code_flow
        type: member
        sso: false
        server_url: "{JIRA[base_url]}"
        credentials:
            token_url: "{JIRA[token_url]}"
            authorization_url: "{JIRA[auth_url]}"
            client_id: "{JIRA[client_id]}"
            client_secret: "{JIRA[client_secret]}"
            scope: "{JIRA[scope]}"
            custom_auth_query:
                audience: "{JIRA[custom_auth_query][audience]}"
    live:
        kind: oauth_auth_code_flow
        type: member
        sso: false
        server_url: "{JIRA[base_url]}"
        credentials:
            token_url: "{JIRA[token_url]}"
            authorization_url: "{JIRA[auth_url]}"
            client_id: "{JIRA[client_id]}"
            client_secret: "{JIRA[client_secret]}"
            scope: "{JIRA[scope]}"
            custom_auth_query:
                audience: "{JIRA[custom_auth_query][audience]}"
