// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: "string",
          pattern: "^password$",
        },
        {
          type: "null",
        },
      ],
      title: "Grant Type",
    },
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
    },
    scope: {
      type: "string",
      title: "Scope",
      default: "",
    },
    client_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Id",
    },
    client_secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      format: "password",
      title: "Client Secret",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "Body_login-login_access_token",
} as const;

export const FeedbackCreateSchema = {
  properties: {
    feedback_type: {
      type: "string",
      maxLength: 50,
      title: "Feedback Type",
    },
    feedback_comment: {
      anyOf: [
        {
          type: "string",
          maxLength: 1000,
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Comment",
    },
    rated_message: {
      anyOf: [
        {
          type: "string",
          maxLength: 5000,
        },
        {
          type: "null",
        },
      ],
      title: "Rated Message",
    },
    user_message_before: {
      anyOf: [
        {
          type: "string",
          maxLength: 5000,
        },
        {
          type: "null",
        },
      ],
      title: "User Message Before",
    },
  },
  type: "object",
  required: ["feedback_type"],
  title: "FeedbackCreate",
} as const;

export const FeedbackPublicSchema = {
  properties: {
    feedback_type: {
      type: "string",
      maxLength: 50,
      title: "Feedback Type",
    },
    feedback_comment: {
      anyOf: [
        {
          type: "string",
          maxLength: 1000,
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Comment",
    },
    rated_message: {
      anyOf: [
        {
          type: "string",
          maxLength: 5000,
        },
        {
          type: "null",
        },
      ],
      title: "Rated Message",
    },
    user_message_before: {
      anyOf: [
        {
          type: "string",
          maxLength: 5000,
        },
        {
          type: "null",
        },
      ],
      title: "User Message Before",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
  },
  type: "object",
  required: ["feedback_type", "id"],
  title: "FeedbackPublic",
} as const;

export const FeedbackUpdateSchema = {
  properties: {
    feedback_type: {
      anyOf: [
        {
          type: "string",
          maxLength: 50,
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Type",
    },
    feedback_comment: {
      anyOf: [
        {
          type: "string",
          maxLength: 1000,
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Comment",
    },
    rated_message: {
      anyOf: [
        {
          type: "string",
          maxLength: 5000,
        },
        {
          type: "null",
        },
      ],
      title: "Rated Message",
    },
    user_message_before: {
      anyOf: [
        {
          type: "string",
          maxLength: 5000,
        },
        {
          type: "null",
        },
      ],
      title: "User Message Before",
    },
  },
  type: "object",
  title: "FeedbackUpdate",
} as const;

export const FeedbacksPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/FeedbackPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "FeedbacksPublic",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const MessageSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
    },
  },
  type: "object",
  required: ["message"],
  title: "Message",
} as const;

export const TokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "Token",
} as const;

export const TokenInfoResponseSchema = {
  properties: {
    is_valid: {
      type: "boolean",
      title: "Is Valid",
    },
    status_message: {
      type: "string",
      title: "Status Message",
    },
    header: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Header",
    },
    payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Payload",
    },
  },
  type: "object",
  required: ["is_valid", "status_message"],
  title: "TokenInfoResponse",
  description: "Response model for token information",
} as const;

export const UserPublicSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    email: {
      anyOf: [
        {
          type: "string",
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    preferred_username: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Preferred Username",
    },
    unique_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Unique Name",
    },
    upn: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Upn",
    },
  },
  type: "object",
  required: ["id"],
  title: "UserPublic",
  description: "User information from IBM Verify JWT token",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const WXOJWTRequestSchema = {
  properties: {
    sso_token: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Sso Token",
    },
    user_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Name",
    },
    custom_user_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Custom User Id",
    },
  },
  type: "object",
  title: "WXOJWTRequest",
  description: "Request model for WXO JWT generation",
} as const;
