// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  GenerateWxoJwtData,
  GenerateWxoJwtErrors,
  GenerateWxoJwtResponses,
  GetOauthConfigData,
  GetOauthConfigResponses,
  GetTokenInfoData,
  GetTokenInfoErrors,
  GetTokenInfoResponses,
  GetWxoConfigData,
  GetWxoConfigResponses,
  IntrospectTokenData,
  IntrospectTokenErrors,
  IntrospectTokenResponses,
  LoginAccessTokenData,
  LoginAccessTokenErrors,
  LoginAccessTokenResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  OauthCallbackData,
  OauthCallbackErrors,
  OauthCallbackResponses,
  OauthLoginData,
  OauthLoginResponses,
  ReadItemData,
  ReadItemErrors,
  ReadItemResponses,
  ReadItemsData,
  ReadItemsErrors,
  ReadItemsResponses,
  ReadUserMeData,
  ReadUserMeResponses,
  RefreshTokenData,
  RefreshTokenErrors,
  RefreshTokenResponses,
  TestTokenData,
  TestTokenResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
  ValidateCompleteFlowData,
  ValidateCompleteFlowErrors,
  ValidateCompleteFlowResponses,
  ValidateTokenSimpleData,
  ValidateTokenSimpleErrors,
  ValidateTokenSimpleResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Oauth {
  /**
   * Get Oauth Config
   *
   * Get OAuth configuration for frontend
   */
  public static getOauthConfig<ThrowOnError extends boolean = false>(
    options?: Options<GetOauthConfigData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetOauthConfigResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/config",
      ...options,
    });
  }

  /**
   * Oauth Login
   *
   * Initiate OAuth login with IBM Verify
   */
  public static oauthLogin<ThrowOnError extends boolean = false>(
    options?: Options<OauthLoginData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      OauthLoginResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/login",
      ...options,
    });
  }

  /**
   * Oauth Callback
   *
   * Handle OAuth callback from IBM Verify
   */
  public static oauthCallback<ThrowOnError extends boolean = false>(
    options: Options<OauthCallbackData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      OauthCallbackResponses,
      OauthCallbackErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/callback",
      ...options,
    });
  }

  /**
   * Refresh Token
   *
   * Refresh the access token
   */
  public static refreshToken<ThrowOnError extends boolean = false>(
    options: Options<RefreshTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      RefreshTokenResponses,
      RefreshTokenErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/refresh",
      ...options,
    });
  }

  /**
   * Logout
   *
   * Logout from IBM Verify by revoking the access token and optionally the refresh token.
   * This invalidates the tokens on IBM Verify's side.
   */
  public static logout<ThrowOnError extends boolean = false>(
    options: Options<LogoutData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LogoutResponses,
      LogoutErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/logout",
      ...options,
    });
  }

  /**
   * Get Token Info
   *
   * Get information about the current token
   */
  public static getTokenInfo<ThrowOnError extends boolean = false>(
    options: Options<GetTokenInfoData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetTokenInfoResponses,
      GetTokenInfoErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/token-info",
      ...options,
    });
  }

  /**
   * Generate Wxo Jwt
   *
   * Generate a JWT token for Watson Orchestrate with encrypted SSO token
   */
  public static generateWxoJwt<ThrowOnError extends boolean = false>(
    options: Options<GenerateWxoJwtData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      GenerateWxoJwtResponses,
      GenerateWxoJwtErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/wxo/jwt",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get Wxo Config
   *
   * Get Watson Orchestrate configuration
   */
  public static getWxoConfig<ThrowOnError extends boolean = false>(
    options?: Options<GetWxoConfigData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetWxoConfigResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/wxo/config",
      ...options,
    });
  }

  /**
   * Introspect Token
   *
   * Introspect an IBM Verify access token using the introspection endpoint.
   * This validates the token with IBM Verify's servers.
   */
  public static introspectToken<ThrowOnError extends boolean = false>(
    options: Options<IntrospectTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      IntrospectTokenResponses,
      IntrospectTokenErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/introspect",
      ...options,
    });
  }

  /**
   * Validate Token Simple
   *
   * Simple token validation - checks what the backend actually validates.
   * This mimics the get_current_user dependency logic.
   */
  public static validateTokenSimple<ThrowOnError extends boolean = false>(
    options: Options<ValidateTokenSimpleData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ValidateTokenSimpleResponses,
      ValidateTokenSimpleErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/validate-token",
      ...options,
    });
  }

  /**
   * Validate Complete Flow
   *
   * Comprehensive validation endpoint that tests the complete token flow:
   * 1. Decode IBM Verify token
   * 2. Introspect with IBM Verify
   * 3. Generate WXO JWT
   * 4. Decode WXO JWT
   *
   * This helps debug token issues end-to-end.
   */
  public static validateCompleteFlow<ThrowOnError extends boolean = false>(
    options: Options<ValidateCompleteFlowData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ValidateCompleteFlowResponses,
      ValidateCompleteFlowErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/oauth/validate-flow",
      ...options,
    });
  }
}

export class Login {
  /**
   * Login Access Token
   *
   * OAuth2 compatible token login, get an access token for future requests
   */
  public static loginAccessToken<ThrowOnError extends boolean = false>(
    options: Options<LoginAccessTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LoginAccessTokenResponses,
      LoginAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      responseType: "json",
      url: "/api/v1/login/access-token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    });
  }

  /**
   * Test Token
   *
   * Test access token
   */
  public static testToken<ThrowOnError extends boolean = false>(
    options?: Options<TestTokenData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      TestTokenResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/login/test-token",
      ...options,
    });
  }
}

export class Users {
  /**
   * Read User Me
   *
   * Get current user information from IBM Verify token.
   *
   * User management is handled by IBM Verify, so this endpoint
   * only returns the user information extracted from the JWT token.
   */
  public static readUserMe<ThrowOnError extends boolean = false>(
    options?: Options<ReadUserMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ReadUserMeResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    });
  }
}

export class Items {
  /**
   * Read Items
   *
   * Retrieve all feedback items (admin only).
   */
  public static readItems<ThrowOnError extends boolean = false>(
    options?: Options<ReadItemsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ReadItemsResponses,
      ReadItemsErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
    });
  }

  /**
   * Create Item
   *
   * Create new feedback item (no authentication required - anonymous feedback).
   */
  public static createItem<ThrowOnError extends boolean = false>(
    options: Options<CreateItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateItemResponses,
      CreateItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/items/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Item
   *
   * Delete a feedback item (admin only).
   */
  public static deleteItem<ThrowOnError extends boolean = false>(
    options: Options<DeleteItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteItemResponses,
      DeleteItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Read Item
   *
   * Get feedback item by ID (admin only).
   */
  public static readItem<ThrowOnError extends boolean = false>(
    options: Options<ReadItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ReadItemResponses,
      ReadItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Update Item
   *
   * Update a feedback item (admin only).
   */
  public static updateItem<ThrowOnError extends boolean = false>(
    options: Options<UpdateItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      UpdateItemResponses,
      UpdateItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
