// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * FeedbackCreate
 */
export type FeedbackCreate = {
  /**
   * Feedback Type
   */
  feedback_type: string;
  /**
   * Feedback Comment
   */
  feedback_comment?: string | null;
  /**
   * Rated Message
   */
  rated_message?: string | null;
  /**
   * User Message Before
   */
  user_message_before?: string | null;
};

/**
 * FeedbackPublic
 */
export type FeedbackPublic = {
  /**
   * Feedback Type
   */
  feedback_type: string;
  /**
   * Feedback Comment
   */
  feedback_comment?: string | null;
  /**
   * Rated Message
   */
  rated_message?: string | null;
  /**
   * User Message Before
   */
  user_message_before?: string | null;
  /**
   * Id
   */
  id: string;
};

/**
 * FeedbackUpdate
 */
export type FeedbackUpdate = {
  /**
   * Feedback Type
   */
  feedback_type?: string | null;
  /**
   * Feedback Comment
   */
  feedback_comment?: string | null;
  /**
   * Rated Message
   */
  rated_message?: string | null;
  /**
   * User Message Before
   */
  user_message_before?: string | null;
};

/**
 * FeedbacksPublic
 */
export type FeedbacksPublic = {
  /**
   * Data
   */
  data: Array<FeedbackPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
  /**
   * Message
   */
  message: string;
};

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * TokenInfoResponse
 *
 * Response model for token information
 */
export type TokenInfoResponse = {
  /**
   * Is Valid
   */
  is_valid: boolean;
  /**
   * Status Message
   */
  status_message: string;
  /**
   * Header
   */
  header?: {
    [key: string]: unknown;
  } | null;
  /**
   * Payload
   */
  payload?: {
    [key: string]: unknown;
  } | null;
};

/**
 * UserPublic
 *
 * User information from IBM Verify JWT token
 */
export type UserPublic = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Preferred Username
   */
  preferred_username?: string | null;
  /**
   * Unique Name
   */
  unique_name?: string | null;
  /**
   * Upn
   */
  upn?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * WXOJWTRequest
 *
 * Request model for WXO JWT generation
 */
export type WxojwtRequest = {
  /**
   * Sso Token
   */
  sso_token?: string | null;
  /**
   * User Name
   */
  user_name?: string | null;
  /**
   * Custom User Id
   */
  custom_user_id?: string | null;
};

export type GetOauthConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/oauth/config";
};

export type GetOauthConfigResponses = {
  /**
   * Response Oauth-Get Oauth Config
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetOauthConfigResponse =
  GetOauthConfigResponses[keyof GetOauthConfigResponses];

export type OauthLoginData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/oauth/login";
};

export type OauthLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OauthCallbackData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
  };
  url: "/api/v1/oauth/callback";
};

export type OauthCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OauthCallbackError = OauthCallbackErrors[keyof OauthCallbackErrors];

export type OauthCallbackResponses = {
  /**
   * Response Oauth-Oauth Callback
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type OauthCallbackResponse =
  OauthCallbackResponses[keyof OauthCallbackResponses];

export type RefreshTokenData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Refresh Token
     */
    refresh_token: string;
  };
  url: "/api/v1/oauth/refresh";
};

export type RefreshTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
  /**
   * Response Oauth-Refresh Token
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type RefreshTokenResponse =
  RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token?: string | null;
  };
  url: "/api/v1/oauth/logout";
};

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Response Oauth-Logout
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetTokenInfoData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Access Token
     */
    access_token: string;
  };
  url: "/api/v1/oauth/token-info";
};

export type GetTokenInfoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTokenInfoError = GetTokenInfoErrors[keyof GetTokenInfoErrors];

export type GetTokenInfoResponses = {
  /**
   * Successful Response
   */
  200: TokenInfoResponse;
};

export type GetTokenInfoResponse =
  GetTokenInfoResponses[keyof GetTokenInfoResponses];

export type GenerateWxoJwtData = {
  body: WxojwtRequest;
  path?: never;
  query?: never;
  url: "/api/v1/wxo/jwt";
};

export type GenerateWxoJwtErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateWxoJwtError =
  GenerateWxoJwtErrors[keyof GenerateWxoJwtErrors];

export type GenerateWxoJwtResponses = {
  /**
   * Response Oauth-Generate Wxo Jwt
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GenerateWxoJwtResponse =
  GenerateWxoJwtResponses[keyof GenerateWxoJwtResponses];

export type GetWxoConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/wxo/config";
};

export type GetWxoConfigResponses = {
  /**
   * Response Oauth-Get Wxo Config
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetWxoConfigResponse =
  GetWxoConfigResponses[keyof GetWxoConfigResponses];

export type IntrospectTokenData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Access Token
     */
    access_token: string;
  };
  url: "/api/v1/oauth/introspect";
};

export type IntrospectTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type IntrospectTokenError =
  IntrospectTokenErrors[keyof IntrospectTokenErrors];

export type IntrospectTokenResponses = {
  /**
   * Response Oauth-Introspect Token
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type IntrospectTokenResponse =
  IntrospectTokenResponses[keyof IntrospectTokenResponses];

export type ValidateTokenSimpleData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Access Token
     */
    access_token: string;
  };
  url: "/api/v1/oauth/validate-token";
};

export type ValidateTokenSimpleErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ValidateTokenSimpleError =
  ValidateTokenSimpleErrors[keyof ValidateTokenSimpleErrors];

export type ValidateTokenSimpleResponses = {
  /**
   * Response Oauth-Validate Token Simple
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ValidateTokenSimpleResponse =
  ValidateTokenSimpleResponses[keyof ValidateTokenSimpleResponses];

export type ValidateCompleteFlowData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Access Token
     */
    access_token: string;
  };
  url: "/api/v1/oauth/validate-flow";
};

export type ValidateCompleteFlowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ValidateCompleteFlowError =
  ValidateCompleteFlowErrors[keyof ValidateCompleteFlowErrors];

export type ValidateCompleteFlowResponses = {
  /**
   * Response Oauth-Validate Complete Flow
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ValidateCompleteFlowResponse =
  ValidateCompleteFlowResponses[keyof ValidateCompleteFlowResponses];

export type LoginAccessTokenData = {
  body: BodyLoginLoginAccessToken;
  path?: never;
  query?: never;
  url: "/api/v1/login/access-token";
};

export type LoginAccessTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAccessTokenError =
  LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginAccessTokenResponse =
  LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type TestTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/login/test-token";
};

export type TestTokenResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type TestTokenResponse = TestTokenResponses[keyof TestTokenResponses];

export type ReadUserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type ReadUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type ReadItemsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items/";
};

export type ReadItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemsError = ReadItemsErrors[keyof ReadItemsErrors];

export type ReadItemsResponses = {
  /**
   * Successful Response
   */
  200: FeedbacksPublic;
};

export type ReadItemsResponse = ReadItemsResponses[keyof ReadItemsResponses];

export type CreateItemData = {
  body: FeedbackCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: FeedbackPublic;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type ReadItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: FeedbackPublic;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type UpdateItemData = {
  body: FeedbackUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type UpdateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
  /**
   * Successful Response
   */
  200: FeedbackPublic;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];
