spec_version: v1
kind: connection
app_id: github_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{GITHUB[base_url]}"
        credentials:
            token: "{GITHUB[token]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{GITHUB[base_url]}"
        credentials:
            token: "{GITHUB[token]}"
