spec_version: v1
kind: connection
app_id: ibm_targetprocess_bearer
environments:
    draft:
        kind: bearer
        type: team
        sso: false
        server_url: "{IBM_TARGETPROCESS[base_url]}"
        credentials:
            token: "{IBM_TARGETPROCESS[bearer_token]}"
    live:
        kind: bearer
        type: team
        sso: false
        server_url: "{IBM_TARGETPROCESS[base_url]}"
        credentials:
            token: "{IBM_TARGETPROCESS[bearer_token]}"