spec_version: v1
kind: connection
app_id: oracle_hcm_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{ORACLE_HCM[base_url]}"
        credentials:
            "base_url": "{ORACLE_HCM[base_url]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{ORACLE_HCM[base_url]}"
        credentials:
            "base_url": "{ORACLE_HCM[base_url]}"