spec_version: v1
kind: connection
app_id: test_servicenow_sso
environments:
  draft:
    kind: oauth_auth_on_behalf_of_flow
    type: member
    sso: true
    server_url: "{SERVICENOW[base_url]}"
    idp_config:
      header:
        content-type: application/x-www-form-urlencoded
      body:
        requested_token_use: on_behalf_of
        requested_token_type: urn:ietf:params:oauth:token-type:saml2
    app_config:
      header:
        content-type: application/x-www-form-urlencode
    identity_provider:
      client_id: "{SERVICENOW[client_id]}"
      client_secret: "{SERVICENOW[client_secret]}"
      scope: "{SERVICENOW[scope]}"
      grant_type: "{SERVICENOW[grant_type]}"
    credentials:
      client_id: "{SERVICENOW[client_id]}"
      access_token_url: "{SERVICENOW[token_url]}"
      grant_type: "{SERVICENOW[grant_type]}"
  live:
    kind: oauth_auth_on_behalf_of_flow
    type: member
    sso: true
    server_url: "{SERVICENOW[base_url]}"
    idp_config:
      header:
        content-type: application/x-www-form-urlencoded
      body:
        requested_token_use: on_behalf_of
        requested_token_type: urn:ietf:params:oauth:token-type:saml2
    app_config:
      header:
        content-type: application/x-www-form-urlencoded
    identity_provider:
      client_id: "{SERVICENOW[client_id]}"
      client_secret: "{SERVICENOW[client_secret]}"
      scope: "{SERVICENOW[scope]}"
      grant_type: "{SERVICENOW[grant_type]}"
    credentials:
      client_id: "{SERVICENOW[client_id]}"
      access_token_url: "{SERVICENOW[token_url]}"
      grant_type: "{SERVICENOW[grant_type]}"
