spec_version: v1
kind: connection
app_id: zendesk_conn_type
environments:
    draft:
        kind: oauth_auth_code_flow
        type: member
        sso: false
        credentials:
            base_url: "{ZENDESK[base_url]}"
            token_url: "{ZENDESK[token_url]}"
            authorization_url: "{ZENDESK[auth_url]}"
            client_id: "{ZENDESK[client_id]}"
            client_secret: "{ZENDESK[client_secret]}"
            scope: "{ZENDESK[scope]}"
    live:
        kind: oauth_auth_code_flow
        type: member
        sso: false
        credentials:
            base_url: "{ZENDESK[base_url]}"
            token_url: "{ZENDESK[token_url]}"
            authorization_url: "{ZENDESK[auth_url]}"
            client_id: "{ZENDESK[client_id]}"
            client_secret: "{ZENDESK[client_secret]}"
            scope: "{ZENDESK[scope]}"