spec_version: v1
kind: connection
app_id: dropbox_oauth2_auth_code
environments:
    draft:
        kind: oauth_auth_code_flow
        type: member
        sso: false
        server_url: "{DROPBOX[base_url]}"
        credentials:
            token_url: "{DROPBOX[token_url]}"
            authorization_url: "{DROPBOX[auth_url]}"
            client_id: "{DROPBOX[client_id]}"
            client_secret: "{DROPBOX[client_secret]}"
    live:
        kind: oauth_auth_code_flow
        type: member
        sso: false
        server_url: "{DROPBOX[base_url]}"
        credentials:
            token_url: "{DROPBOX[token_url]}"
            authorization_url: "{DROPBOX[auth_url]}"
            client_id: "{DROPBOX[client_id]}"
            client_secret: "{DROPBOX[client_secret]}"