spec_version: v1
kind: connection
app_id: openpages_key_value
environments:
    draft:
        kind: key_value
        type: team
        sso: false
        server_url: "{OPENPAGES[base_url]}"
        credentials:
              token_url: "{OPENPAGES[token_url]}"
              client_id: "{OPENPAGES[client_id]}"
              client_secret: "{OPENPAGES[client_secret]}"
              base_url: "{OPENPAGES[base_url]}"
    live:
        kind: key_value
        type: team
        sso: false
        server_url: "{OPENPAGES[base_url]}"
        credentials:
              token_url: "{OPENPAGES[token_url]}"
              client_id: "{OPENPAGES[client_id]}"
              client_secret: "{OPENPAGES[client_secret]}"
              base_url: "{OPENPAGES[base_url]}"
